---
dist: xenial
sudo: false
language: python

addons:
  postgresql: "9.4"

# LOL!
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36-django111-wagtail23
    - python: 3.6
      env: TOXENV=py36-django22-wagtail26
    - python: 3.7
      env: TOXENV=py37-django111-wagtail23
    - python: 3.7
      env: TOXENV=py37-django22-wagtail26

  allow_failures:
    - python: 3.6
      env: TOXENV=lint

install:
  - pip install tox codecov


script:
  - tox


after_success:
  - tox -e coverage-report
  - codecov
