exclude = ["dist","build","venv",".venv",".tox",".git"]
line-length = 88
target-version = "py38"

[lint]
ignore = [
    "E501", # line too long
]

extend-select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "BLE",  # flake8-blind-except
    "C4",   # flake8-comprehensions
    "PT",   # flake8-pytest-style
    "S",    # flake8-bandit
    "T10",  # flake8-debugger
    "T20",  # flake8-print
    "UP",   # pyupgrade
    "W",    # pycodestyle warnings
]

[lint.extend-per-file-ignores]
"tests/test_*.py" = [
    "S101", # flake8-bandit Use of assert detected
]

[lint.isort]
known-first-party = ["src"]
