# Generated by Django 4.0.10 on 2023-05-16 04:25

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations

import tests.testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_pagewithnestedstreamblock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mytestpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "char_array",
                        wagtail.blocks.ListBlock(wagtail.blocks.CharBlock()),
                    ),
                    (
                        "int_array",
                        wagtail.blocks.ListBlock(wagtail.blocks.IntegerBlock()),
                    ),
                    (
                        "struct",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=100)),
                                (
                                    "item",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("label", wagtail.blocks.CharBlock()),
                                            ("value", wagtail.blocks.IntegerBlock()),
                                        ]
                                    ),
                                ),
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        tests.testapp.models.MyBlockItem
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("page", wagtail.blocks.PageChooserBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("document", wagtail.documents.blocks.DocumentChooserBlock()),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="pagewithnestedstreamblock",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "inner_stream",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "struct_block",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "title",
                                                wagtail.blocks.CharBlock(
                                                    max_length=100
                                                ),
                                            ),
                                            (
                                                "item",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "label",
                                                            wagtail.blocks.CharBlock(),
                                                        ),
                                                        (
                                                            "value",
                                                            wagtail.blocks.IntegerBlock(),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            (
                                                "items",
                                                wagtail.blocks.ListBlock(
                                                    tests.testapp.models.MyBlockItem
                                                ),
                                            ),
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=False
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                ("char_block", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="pagewithsimplestructblocknested",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "inner_stream",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "simple_struct_block",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("text", wagtail.blocks.CharBlock()),
                                            ("number", wagtail.blocks.IntegerBlock()),
                                            ("boolean", wagtail.blocks.BooleanBlock()),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="pagewithstreamblock",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "struct_block",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(max_length=100)),
                                (
                                    "item",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("label", wagtail.blocks.CharBlock()),
                                            ("value", wagtail.blocks.IntegerBlock()),
                                        ]
                                    ),
                                ),
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        tests.testapp.models.MyBlockItem
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("char_block", wagtail.blocks.CharBlock()),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="pagewithstreamblockinlistblock",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "list_block",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StreamBlock(
                                [
                                    (
                                        "struct_block",
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        max_length=100
                                                    ),
                                                ),
                                                (
                                                    "item",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "label",
                                                                wagtail.blocks.CharBlock(),
                                                            ),
                                                            (
                                                                "value",
                                                                wagtail.blocks.IntegerBlock(),
                                                            ),
                                                        ]
                                                    ),
                                                ),
                                                (
                                                    "items",
                                                    wagtail.blocks.ListBlock(
                                                        tests.testapp.models.MyBlockItem
                                                    ),
                                                ),
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                            ]
                                        ),
                                    ),
                                    ("char_block", wagtail.blocks.CharBlock()),
                                ]
                            )
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="pagewithstreamblockinstructblock",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "struct_block",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "inner_stream",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "struct_block",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                max_length=100
                                                            ),
                                                        ),
                                                        (
                                                            "item",
                                                            wagtail.blocks.StructBlock(
                                                                [
                                                                    (
                                                                        "label",
                                                                        wagtail.blocks.CharBlock(),
                                                                    ),
                                                                    (
                                                                        "value",
                                                                        wagtail.blocks.IntegerBlock(),
                                                                    ),
                                                                ]
                                                            ),
                                                        ),
                                                        (
                                                            "items",
                                                            wagtail.blocks.ListBlock(
                                                                tests.testapp.models.MyBlockItem
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            ),
                                            ("char_block", wagtail.blocks.CharBlock()),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
